[package]
name = "dental-db"
version = "0.1.0"
edition = "2021"

[dependencies]
dental-common = { path = "../dental-common" }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "uuid", "chrono", "json"] }
